[package]
name = "chaum_pedersen"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4.6", features = ["rand"] }
rand = "0.8"
hex = "0.4.3"
num-traits = "0.2.19"

[lib]
crate-type = ["lib"]